XacademyTeam6/cursosNoc

- back/controllers/userController.js
- back/middleware/login.validation.middleware.js
- back/providers/userProvider.js
- back/routes/userRouters.js
- back/services/userService.js
validación email, password simple
> Rutas-corregidas-adiccion-validacion

- back/providers/userProvider.js
Agregada la encriptacion del password usuario
> encypt-password

- back/middleware/user.validation.middleware.js
Se corrige las variables de la validacion de usuario que estaban en español.
> BE - Correccion validacion crear usuario

- back/controllers/courseController.js
- back/migrations/20230825011104-create-course.js
- back/models/course.js
- back/providers/courseProvider.js
- back/routes/courseRoutes.js
- back/routes/index.js
- back/services/courseService.js
Se agrega la entidad curso, compuesta por su modelo, migración y operaciones de crear, leer, modificar y eliminar.
- POST /api/course { "name": [nombre] }
- GET /api/course
- GET /api/course/[id]
- PUT /api/course/[id] { "name": [nombre] }
- DELETE /api/course/[id]
> Añadir CRUD de cursos a la API

- front/src/app/modules/login/components/login/login.component.html
- front/src/app/modules/login/login.module.ts
- front/src/app/modules/register/components/register/register.component.html
- front/src/app/modules/register/register.module.ts
- front/src/app/modules/shared/components/footer/footer.component.css
- front/src/app/modules/shared/components/footer/footer.component.html
Resubo cambios al parecer me habia faltado hacer un commit.
> Corrijo NavBar y Footer en register

- back/controllers/authController.js
- front/src/app/modules/login/components/login/login.component.html
- front/src/app/modules/login/components/login/login.component.ts
- front/src/app/modules/login/login.module.ts
- front/src/app/services/auth.service.spec.ts
- front/src/app/services/auth.service.ts
- front/src/config.ts
Se conecto el BE con el FE en el login
> Conexion login

- front/src/app/modules/login/components/login/login.component.css
- front/src/app/modules/login/components/login/login.component.html
- front/src/app/modules/login/components/login/login.component.ts
- front/src/styles.css
Se corrige el error en la validacion del login.
> FE - Corregir bug validacion login

- front/src/app/app-routing.module.ts
- front/src/app/guards/no-auth/no-auth.guard.spec.ts
- front/src/app/guards/no-auth/no-auth.guard.ts
- front/src/app/modules/home/components/home/home.component.html
corregido el bug de "logeados" pueden ir a pagina de login y registro
> agregado noAuth guard

- front/src/app/app-routing.module.ts
- front/src/app/modules/contact/components/contact/contact.component.css
- front/src/app/modules/contact/components/contact/contact.component.html
- front/src/app/modules/contact/components/contact/contact.component.spec.ts
- front/src/app/modules/contact/components/contact/contact.component.ts
- front/src/app/modules/contact/contact-routing.module.ts
- front/src/app/modules/contact/contact.module.ts
- front/src/app/modules/shared/components/navbar/navbar.component.html
Se crea Modulo y componente contact y formulario de contacto con  boton para enviar la consulta.
> FE - Crear Modulo y componente contact

- front/src/app/modules/login/components/login/login.component.css
- front/src/app/modules/register/components/register/register.component.css
- front/src/app/modules/register/components/register/register.component.html
- front/src/app/modules/register/components/register/register.component.ts
- front/src/app/modules/shared/components/footer/footer.component.css
- front/src/app/modules/shared/components/navbar/navbar.component.css
- front/src/styles.css
Se corrige el estilo de la pagina de registro
> Estilo registro

- back/controllers/courseController.js
- back/models/course.js
- back/models/index.js
- back/models/user.js
- back/providers/courseProvider.js
- back/routes/courseRoutes.js
- back/services/courseService.js
Las tablas se crean automáticamente en base a los modelos.
Ya no son necesarias las migraciones.
La relación se registra en la tabla de asociación UserCourses, creada automáticamente.
POST y GET de /api/course/{id}/user para crear y obtener usuarios de un curso, para probar la nueva relación.
> Relación de usuarios y cursos

- front/src/app/modules/login/components/login/login.component.css
- front/src/app/modules/login/components/login/login.component.html
- front/src/app/modules/register/components/register/register.component.css
Se Eliminar footer y nvbbar
Se Agregar logo de incubadora sobre palabra “Login” (Cambiar a “Iniciar sesion”
Se Aumentar espacio entre input y “no tienes cuenta?”
Se colocar el mismo tamaño de input y boton
> FE - Modificar vista login

- back/migrations/20230307002718-create-user.js
- back/migrations/20230825011104-create-course.js
- back/models/course.js
- back/models/user.js
- back/providers/courseProvider.js
- back/providers/userProvider.js
Soft-delete implementado, modificado getUsers/getCourses para que muestre los cursos que han sido eliminados
> Soft-delete implementado

- front/src/app/models/user.model.ts
- front/src/app/modules/shared/components/navbar/navbar.component.html
- front/src/app/modules/user/components/user-list/user-list.component.html
- front/src/app/modules/user/components/user-list/user-list.component.spec.ts
- front/src/app/modules/user/components/user-list/user-list.component.ts
- front/src/app/modules/user/components/user/user.component.html
- front/src/app/modules/user/components/user/user.component.ts
- front/src/app/modules/user/user-routing.module.ts
- front/src/app/modules/user/user.module.ts
- front/src/app/services/user.service.spec.ts
- front/src/app/services/user.service.ts
Se crea componente user-list y se agrega al user.component.html y se agrega usuarios al navbar cuando se esta logueado para corroborar su funcionamiento.
> Se crea componente user-list

- back/controllers/courseController.js
- back/controllers/userController.js
- back/migrations/20230307002718-create-user.js
- back/models/user.js
- back/package.json
- back/providers/courseProvider.js
- back/providers/userProvider.js
- back/services/courseService.js
- back/services/userService.js
"role" es de tipo ENUM. Acepta solo los valores "admin", "teacher" y "student".
ej. GET /user?role=student
npm run db:restart. Elimina y crea la base de datos.
> Roles de usuario

- front/src/app/modules/register/components/register/register.component.ts
- front/src/app/modules/user/components/add-user/add-user.component.css
- front/src/app/modules/user/components/add-user/add-user.component.html
- front/src/app/modules/user/components/add-user/add-user.component.spec.ts
- front/src/app/modules/user/components/add-user/add-user.component.ts
- front/src/app/modules/user/components/user-list/user-list.component.css
- front/src/app/modules/user/components/user-list/user-list.component.html
- front/src/app/modules/user/user-routing.module.ts
- front/src/app/modules/user/user.module.ts
- front/src/app/services/user.service.ts
Se crea el componente add-user y se agrega el formulario para la carga de nuevos usuarios con su respectivo rol y se crea boton "Nuevo Usuario" en lista de usuarios. Se cambia direccion del servidor en register por variable baseURL.
> Se crea el componente add-user

- back/controllers/courseController.js
- back/controllers/userController.js
- back/providers/courseProvider.js
- back/providers/userProvider.js
- back/routes/courseRoutes.js
- back/routes/userRoutes.js
- back/services/courseService.js
- back/services/userService.js
- _GET /user/:id/course_ obtiene los cursos del usuario
- _PUT /course/:courseId/user/:userId_ agrega el usuario al curso (el usuario ya debe existir)
- _DELETE /course/:id/user/:userId_ quita el usuario del curso
> Endpoints para manejar las relaciones entre usuarios y cursos

- front/src/app/modules/login/components/login/login.component.css
- front/src/app/modules/user/components/add-user/add-user.component.css
- front/src/app/modules/user/components/add-user/add-user.component.html
- front/src/app/modules/user/components/user/user.component.html
- front/src/app/modules/user/components/user/user.component.ts
- front/src/app/services/user.service.ts
Se Agrega el botón “borrar” en la vista del detalle de usuario con la lógica necesaria para se elimine de la base de datos.
> Agregar boton borrar en detalle de usuario

- front/src/app/modules/user/components/edit-user/edit-user.component.html
- front/src/app/modules/user/components/edit-user/edit-user.component.ts
> al editar usuario, volver al mismo usuario y no la lista

- front/src/app/modules/news/components/news/news.component.css
- front/src/app/modules/news/components/news/news.component.html
- front/src/app/modules/news/components/news/news.component.spec.ts
- front/src/app/modules/news/components/news/news.component.ts
- front/src/app/modules/news/news-routing.module.ts
- front/src/app/modules/news/news.module.ts
- front/src/app/modules/shared/components/navbar/navbar.component.html
- front/src/app/services/news.service.spec.ts
- front/src/app/services/news.service.ts
Se realiza el Front del componente news
> FE - crear la pagina de noticias, con tarjetas hardcodeadas

- back/controllers/courseController.js
- back/providers/courseProvider.js
- back/routes/courseRoutes.js
- back/services/courseService.js
- front/src/app/services/course.service.ts
Se corrige la busqueda de cursos
> Se corrige buscador de cursos

- front/src/app/modules/course/components/add-course/add-course.component.css
- front/src/app/modules/course/components/add-course/add-course.component.html
- front/src/app/modules/course/components/add-course/add-course.component.spec.ts
- front/src/app/modules/course/components/add-course/add-course.component.ts
- front/src/app/modules/course/components/edit-course/edit-course.component.html
- front/src/app/modules/course/components/edit-course/edit-course.component.spec.ts
- front/src/app/modules/course/components/edit-course/edit-course.component.ts
- front/src/app/modules/course/course-routing.module.ts
- front/src/app/modules/course/course.module.ts
Se crea el componente add-course con la logica para crear cursos.
> FE -Crear componente add-course

- back/controllers/authController.js
- back/providers/userProvider.js
- back/routes/index.js
- back/services/authService.js
- front/package.json
- front/src/app/modules/login/components/login/login.component.html
- front/src/app/modules/login/components/login/login.component.ts
- front/src/app/services/auth.service.ts
> Authservice token

- front/src/app/modules/register/components/register/register.component.html
- front/src/app/modules/register/components/register/register.component.ts
Se modifico el componente register
> Quitar redireccion a login en registro fallido

- front/src/app/modules/shared/components/navbar/navbar.component.ts
- front/src/app/modules/user/components/add-user/add-user.component.html
- front/src/app/modules/user/components/add-user/add-user.component.ts
- front/src/app/modules/user/components/edit-user/edit-user.component.ts
- front/src/app/modules/user/components/user/user.component.ts
toastr en: add-user
toastr en edit-user
toastr en delete user
> Se agreagan Toast

- back/migrations/20230307002718-create-user.js
- back/models/user.js
- back/services/authService.js
Agrega el rol del usuario al payload del JWT devuelto en /auth/login y establece "student" como el rol de usuario por defecto.
> Rol del usuario en token + rol "student" predeterminado

- front/angular.json
- front/package.json
- front/src/app/modules/shared/components/navbar/navbar.component.css
- front/src/app/modules/shared/components/navbar/navbar.component.html
- front/src/app/modules/shared/components/navbar/navbar.component.ts
- front/src/app/services/auth.service.ts
- front/src/app/services/news.service.ts
Dentro del menu se colocaron los links de Mi Perfil, Mis cursos y Salir
Tambien se eliminaron noticias y se dejaron solo las dos del face del noc por error en algunas y diferente tamaño en las imagenes.
> Mostrar nombre de usuario en navbar con menu desplegable

- front/src/app/modules/user/components/edit-user/edit-user.component.css
- front/src/app/modules/user/components/edit-user/edit-user.component.html
Modificación css del componente edit-user
> css modificado

- front/angular.json
- front/package.json
- front/src/app/modules/course/components/course/course.component.html
- front/src/app/modules/course/components/course/course.component.ts
- front/src/app/modules/course/components/my-courses/my-courses.component.html
- front/src/app/modules/course/components/my-courses/my-courses.component.spec.ts
- front/src/app/modules/course/components/my-courses/my-courses.component.ts
- front/src/app/modules/course/course-routing.module.ts
- front/src/app/modules/course/course.module.ts
- front/src/app/modules/login/components/login/login.component.css
- front/src/app/modules/shared/components/navbar/navbar.component.css
- front/src/app/modules/shared/components/navbar/navbar.component.html
- front/src/app/modules/user/components/user/user.component.html
- front/src/app/modules/user/components/user/user.component.ts
Se agrega Modal de confirmación al eliminar cursos y usuarios
> Modal en eliminar cursos y usuarios

- front/src/app/modules/course/components/course-list/course-list.component.css
- front/src/app/modules/course/components/course-list/course-list.component.html
- front/src/app/modules/course/components/course/course.component.css
- front/src/app/modules/course/components/course/course.component.html
- front/src/app/modules/course/components/edit-course/edit-course.component.css
- front/src/app/modules/course/components/edit-course/edit-course.component.html
- front/src/app/modules/course/components/edit-course/edit-course.component.ts
- front/src/app/modules/shared/components/navbar/navbar.component.css
- front/src/app/modules/shared/components/navbar/navbar.component.html
- front/src/app/modules/user/components/edit-user/edit-user.component.css
- front/src/app/modules/user/components/edit-user/edit-user.component.html
- front/src/app/modules/user/components/edit-user/edit-user.component.ts
- front/src/app/modules/user/components/user-list/user-list.component.css
- front/src/app/modules/user/components/user-list/user-list.component.html
- front/src/app/modules/user/components/user/user.component.css
- front/src/app/modules/user/components/user/user.component.html
- front/src/styles.css
Se Editaron botones detalles, editar y borrar y se agegaron botones "Volver" tambien se agrego hover al navbar
> Editar botones detalles, editar y borrar

- front/src/app/modules/user/components/edit-user/edit-user.component.css
- front/src/app/modules/user/components/edit-user/edit-user.component.html
- front/src/app/modules/user/components/edit-user/edit-user.component.ts
se corregen eerores en edit-user
> Correccion de errorres

- front/src/app/models/course.model.ts
- front/src/app/modules/course/components/add-course/add-course.component.html
- front/src/app/modules/course/components/add-course/add-course.component.ts
- front/src/app/modules/course/components/course-list/course-list.component.html
- front/src/app/modules/course/components/course/course.component.html
- front/src/app/modules/course/components/edit-course/edit-course.component.html
- front/src/app/modules/shared/components/card/card.component.css
Se agrego el atributo horas en el front de  cursos
> Se agrega horas en front

- front/src/app/modules/register/components/register/register.component.css
- front/src/app/modules/register/components/register/register.component.html
Se agrega "¿Ya tienes cuenta? Ingresa aquí" a registro con  la redireccion a login y se retoca el css
> Se agrega ¿Ya tienes cuenta? Ingresa aquí a registro

- front/src/app/modules/shared/components/card/card.component.html
- front/src/app/modules/shared/components/card/card.component.ts
- front/src/app/services/course.service.ts
Se configura el boton Incribirse para que realice la inscripcion al curso seleccionado y se agrega toasts de registro exitoso. Se configura el boton para que si Al hacer clic no esta logueado, se redirecciona a login.
> Se configura el boton Incribirse
